// Generated by gencpp from file example1_pkg/answer.msg
// DO NOT EDIT!


#ifndef EXAMPLE1_PKG_MESSAGE_ANSWER_H
#define EXAMPLE1_PKG_MESSAGE_ANSWER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace example1_pkg
{
template <class ContainerAllocator>
struct answer_
{
  typedef answer_<ContainerAllocator> Type;

  answer_()
    : sum(0)  {
    }
  answer_(const ContainerAllocator& _alloc)
    : sum(0)  {
  (void)_alloc;
    }



   typedef int32_t _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::example1_pkg::answer_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::example1_pkg::answer_<ContainerAllocator> const> ConstPtr;

}; // struct answer_

typedef ::example1_pkg::answer_<std::allocator<void> > answer;

typedef boost::shared_ptr< ::example1_pkg::answer > answerPtr;
typedef boost::shared_ptr< ::example1_pkg::answer const> answerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::example1_pkg::answer_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::example1_pkg::answer_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::example1_pkg::answer_<ContainerAllocator1> & lhs, const ::example1_pkg::answer_<ContainerAllocator2> & rhs)
{
  return lhs.sum == rhs.sum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::example1_pkg::answer_<ContainerAllocator1> & lhs, const ::example1_pkg::answer_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace example1_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::example1_pkg::answer_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::example1_pkg::answer_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::example1_pkg::answer_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::example1_pkg::answer_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::example1_pkg::answer_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::example1_pkg::answer_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::example1_pkg::answer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0ba699c25c9418c0366f3595c0c8e8ec";
  }

  static const char* value(const ::example1_pkg::answer_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0ba699c25c9418c0ULL;
  static const uint64_t static_value2 = 0x366f3595c0c8e8ecULL;
};

template<class ContainerAllocator>
struct DataType< ::example1_pkg::answer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "example1_pkg/answer";
  }

  static const char* value(const ::example1_pkg::answer_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::example1_pkg::answer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 sum\n"
;
  }

  static const char* value(const ::example1_pkg::answer_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::example1_pkg::answer_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct answer_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::example1_pkg::answer_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::example1_pkg::answer_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    Printer<int32_t>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXAMPLE1_PKG_MESSAGE_ANSWER_H
